version: 3
endpoint: https://uncommon-foal-23.hasura.app
admin_secret: sgwUQpn2pMevAdlbgNJpNO7AmWgK82oukC9rZ50PErx9oCgvC2goO6q6OQRrbCn9
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
